src/mac-current-connections.js
For some reason at first this worked just fine but when i started using `node-wifi` in Electron, i wasn't able to get any connections with this.
This change i've made fixed the issue, at least for me.
macOS Sierra, version: 10.12.4 (16E195)
I couldn't decide which is better:
```javascript
connection.frequency = parseInt(networkUtils.frequencyFromChannel(parseInt(line.match(/[ ]*channel: (.*)/)[1])));
```
or:
```javascript
connection.frequency = parseInt(networkUtils.frequencyFromChannel(parseInt(line.match(/[ ]*channel: (.*)/)[1].split(',')[0])));
```
=> Fixed channel/frequency in `mac-current-connections.js`

README.md, src/windows-connect.js, src/windows-current-connections.js, src/windows-disconnect.js, src/windows-scan.js
We are using this library in Windows, and we detected that `connectToWifi`'s callback is called when Windows is told to connect to the network instead of waiting for it to actually connect.
I changed its behaviour, so it waits until `netsh wlan connect` is done and the profile XML is deleted.
Additionally, if the connection fails, the function also takes care of deleting the created connection profile.
=> Wait until device is connected, delete profile if connection fails

package-lock.json, package.json
npm audit found vulnerability "Prototype Pollution" in package "deep-extend" that used in package "table-layout" and "table-layout" used in "command-line-usage". The vulnerability was patched in version ">=0.5.1" of "command-line-usage". So I updated "command-line-usage" to version 5.0.5.
=> package command-line-usage was upgraded to 5.0.5

src/mac-connect.js
When trying to connect to a wifi that was not there in the first place. The method returned a success instead of error.
=> correctly return error if network is not found

src/windows-connect.js
I was having problems to connect to a network using my 2nd wi-fi interface on Windows 10.
I executed the command manualy and the error seemed to be a missing argument. Than noticed that passing the `interface="intf"` argument, the command works. I think it's because I have more than one interfaces connected to my pc, so I have to tell `netsh` what interface I want to use.
Already tested this PR in my PC, and it's working. I don't think this extra argument could impact other behaviours.
=> Fixed Windows netsh missing argument problem

src/linux-connect.js, src/linux-current-connections.js, src/linux-disconnect.js, src/linux-scan.js, src/mac-connect.js, src/mac-current-connections.js, src/mac-scan.js, src/windows-connect.js, src/windows-current-connections.js, src/windows-disconnect.js, src/windows-scan.js
The `env` should be a property of an options Object and should not be passed directly. By sending it directly it will clash with other libraries that are trying to override `exec` `Options`. In my case, this is `pkg` library, see: https://github.com/zeit/pkg/blob/master/prelude/bootstrap.js#L1336
See `child_process.exec` docs: https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback
=> fix child_process.exec options format

src/windows-scan.js
- avoid parsing empty networks.
- verify that each network field is defined before trying to parse it.
=> fixed empty network fields parsing as per #72

src/windows-connect.js
No need to use SSID name as filename. 
The problem is, that if the SSID contains a colon the connect process on windows fails.
Tested with Win10
=> Don't use SSID name as xml name when connecting on windows

src/linux-scan.js
in some platforms (raspberry pi for instance) providing the iface option prepends that same iface declaration to the output. this is hanging up this loop as the very next line assumes every line has colons. this quick check will skip any lines without required colon delimiters.
=> sanity check for colon

bin/wifi.js
Fixes broken CLI.
Following error message appear when installing a fresh version of  node-wifi and using  the cli:
```
/node-wifi/node_modules/chalk/templates.js:109
throw new Error('Found extraneous } in Chalk template literal');
^
Error: Found extraneous } in Chalk template literal
```
The string syntax was adopted to the latest [chalk](https://github.com/chalk/chalk) syntax.
Make the CLI usable again.
```
wifi --scan
```
Manual tests on Linux and MacOS.
=> fix: adapt chalk string syntax

src/windows-connect.js
The network profile add command is being executed with wrong filename.
Fixes issue #78
=> fix: windows connection profile execute

src/windows-connect.js
Fix for Wifi connect issue on Windows
1.  Current windows connect implementation does not work due to wrong command usage. This PR fixes it.
2. Also, delete local profile file fail on Windows because of shell options missing in execFile call.
Detail for the fix is explained here: https://stackoverflow.com/a/54515183/8592525
Manual testing on Windows 10.
Issue link: https://github.com/friedrith/node-wifi/issues/111
=> fix: wifi connect issue fix for Windows

src/linux-current-connections.js, src/linux-scan.js
Fixes not full list of scanned networks and current connections on linux
`wifi --scan`
`wifi --current`
Manual tests on Linux
=> fix: linux scan and getCurrentConnections

src/mac-connect.js
[Related issue](https://github.com/quasarframework/quasar/issues/5495)
The **connect** doesn't work on a mac when developing a [quasar](https://quasar.dev/quasar-cli/developing-electron-apps/introduction) electron application.
It doesn't work because when quasar launches the electron app (it uses [webpack](https://webpack.js.org/)) it doesn't have access to the same PATH, and so, node can't find the _networksetup_ tool.
Motivation for this PR is that it won't change anything for "normal" electron users, but make win some useful time for quasar users (as for other frameworks of that kind). 
Nothing changes for end the usages of node-wifi library. 
Need to have an quasar electron app to see that error. 
Tested as it is asked in test/README.md, using a .env file and running the tests (on a …
=> Error when connect on a quasar electron app on mac

package.json
In order to see the registry in github page, the URL is provided in package.json
With now several registry available (github, npm, etc), it may be useful to show the current registry used.
=> docs: change registry config to see it in github page

.eslintrc.json, CONTRIBUTING.md, package-lock.json, package.json, src/__test__/unlogger.js, src/mac-scan.js, src/macOS/scan/__logs__/scan-01.log, src/macOS/scan/__test__/parser.spec.js, src/macOS/scan/command.js, src/macOS/scan/parser.js, src/utils/__test__/promiser.spec.js, src/utils/executer.js, src/utils/promiser.js, test/scan.js
- split the function to scan networks on macos to simplify tests.
- add a command `npm run test`
=> refactor(macos/scan): split into several files to simplify tests

.travis.yml, package.json, src/mac-scan.js, src/macOS/scan/__logs__/scan-shifted.log, src/macOS/scan/__logs__/scan-space.log, src/macOS/scan/__test__/parser.spec.js, src/macOS/scan/command.js, src/macOS/scan/parser.js, src/utils/__test__/promiser.spec.js, src/utils/executer.js, src/utils/promiser.js, test/scan.js
A line was shifted in airport output (cf scan-shifted.log) and it was breaking parser for this line. It is now fixed
=> fix(macos/scan): parse networks when shifted

.github/workflows/test.yml
For a better readibility in pull requests, the workflow is now renamed "test" and is splited in two jobs: lint and unit tests
Previous workflow config had been generated by github and was not very understandable
No impact on API.
Tested on CI
=> ci: split workflow in separated jobs

.github/workflows/build.yml
Workflow is now called `build` instead of `test`.
In the future, in order to use `import` syntax, javascript code should be built so the name build is more adapted.
No API change
CI
=> ci: rename workflow into build to prepare es6 modules import

README.md
Status badge was still travis ci status. It is now build workflow status on github actions.
Roadmap is also updated.
=> docs: update status badge with github actions

BIBLIOGRAPHY.md, README.md, docs/hardware.md, scripts/scan.js, src/index.js, src/linux-scan.js, src/linux/index.js, src/linux/scan/__logs__/scan-01.log, src/linux/scan/__test__/command.spec.js, src/linux/scan/__test__/parser.spec.js, src/linux/scan/command.js, src/linux/scan/index.js, src/linux/scan/parser.js, src/platform.js
Code to scan wifi on linux is not easier to read and also tested.
It also introduce a new architecture to more easily manage all functions
from all platforms.
Use architecture based on folders and `command` and `parser`.
It is easier to unitary tests parser and command generator.
No change of interfaces.
Unit tests have been added
=> refactor(linux): scan easier to read

src/windows-scan.js
While scanning for the networks in windows, initially there is a slicing from 5th index which leads to the omitting of first row depicting the ssid of the network.
Have changed the slicing from 4th index, so that all the network information be preserved and assigned correctly.
This change is required as to get the correct information of the first network been captured and utilized.
https://github.com/friedrith/node-wifi/issues/137
After the change, have tried to scan for the networks, and can see all the information for every network is been listed correctly.
Also tried to connect and disconnect with the selected network, which works as expected.
- [x ] Bug fix (non-breaking change which fixes an issue)
=> fix: windows wifi scan issue fix for first network

src/windows-connect.js
While connecting to a network in windows by a non-admin user, the connection fails if the project/package-workspace is under some restricted location (Ex: Program Files) because the nodeWifiConnect.xml is created is not getting created due to permission issues.
Changed the location of nodeWifiConnect.xml to be created in a temporary directory (C:\Users<userId>\AppData\Local\Temp) so that work flow is uninterrupted for non-admin user also.
This change is required as all window users (Admin and Non-Admin) should be able to connect to the network.
#159 
After the required changes are done, we tried to connect to the network in a non-admin user machine, which works as expected.
=> fix(windows): connect network for non-admin users
